### ISSUE TITLE
After upgrading from 3.1 to 3.2: ImportError: cannot import name Celery

### ISSUE THREAD

**Issue by Johnson145** [WeblateOrg/weblate#2410]
**Describe the bug**
I've just upgraded from 3.1.1 to 3.2.2. Unfortunately, I can't get Weblate working again, because of an import error with the new Celery dependency. Here is the full error from the log:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/weblate/wsgi.py", line 44, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python2.7/dist-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 22, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/weblate/__init__.py", line 26, in <module>
    from weblate.celery import app as celery_app
  File "/usr/local/lib/python2.7/dist-packages/weblate/celery.py", line 26, in <module>
    from celery import Celery
  File "/usr/local/lib/python2.7/dist-packages/weblate/celery.py", line 26, in <module>
    from celery import Celery
ImportError: cannot import name Celery
Tue Nov 27 12:08:58 2018 - unable to load app 0 (mountpoint='') (callable not found or import error)
```
As you can see Weblate is installed using pip. Celery is installed, too. If I manually run `python` and `ImportError: cannot import name Celery` no error occurs. I tried to use the provided default configurations for Celery (the one for testing as well as the one for prodution). I followed [this](https://docs.weblate.org/en/latest/admin/install.html#celery) to configure Celery.

**Server configuration and status**
Please paste the output of `list_versions` and `check --deploy` commands over
here. Depending on installation these can be executed in different way, please
consult https://docs.weblate.org/en/latest/admin/management.html for more
details.

```
weblate list_versions
 * Weblate 3.2.2
 * Python 2.7.12
 * Django 1.11.16
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.11.0
 * social-auth-core 2.0.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.1
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.7.4
 * Pillow 5.3.0
 * python-dateutil 2.7.5
 * lxml 4.2.5
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.9.0
 * user-agents 1.1.0
 * jellyfish 0.6.1
 * pytz 2018.7
 * pyuca 1.2
 * python-bidi 0.4.0
 * PyYAML 3.13
 * Mercurial 3.7.3
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Platform: Linux 4.4.0 (x86_64)
```

```
weblate check --deploy
System check identified some issues:

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.

System check identified 1 issue (0 silenced).
```

Any help is apprediated very much!

**Comment by nijel** [comment]
Most likely this is caused by wrong Python path in the environment you're using to start Weblate. Are you adding `/usr/local/lib/python2.7/dist-packages/weblate` to Python path at some poing (eg. in uwsgi or what are you using to start the wsgi)? 

See https://stackoverflow.com/a/25029933/225718 for more information.

**Comment by ardijyrgens** [comment]
Encountered the same error after upgrading from 3.1 to 3.6 on Ubuntu 16.04.6. 

Uwsgi fails to start Weblate with the following error:

` File "/usr/local/lib/python2.7/dist-packages/weblate/__init__.py", line 26, in <module>
    from weblate.celery import app as celery_app
  File "/usr/local/lib/python2.7/dist-packages/weblate/celery.py", line 26, in <module>
    from celery import Celery
  File "/usr/local/lib/python2.7/dist-packages/weblate/celery.py", line 26, in <module>
    from celery import Celery`

Yes. The following is in the Uwsgi init file as @nijel predicts in the previous discussion. 

"python-path   = /usr/local/lib/python2.7/dist-packages/weblate/"

But unfortuntaley if it is removed another error is ecountered: 

`Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/weblate/wsgi.py", line 44, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python2.7/dist-packages/django/core/wsgi.py", line 14, in get_wsgi_application
    return WSGIHandler()
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 151, in __init__
    self.load_middleware()
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 80, in load_middleware
    middleware = import_string(middleware_path)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named middleware`

Any ideas what might cause this? 

Weblate is installed via Pip 

pip show weblate
`pip show weblate
Name: Weblate
Version: 3.6.1
Summary: A web-based localization tool with tight version control integration
Home-page: https://weblate.org/
Author: Michal Čihař
Author-email: michal@cihar.com
License: GPLv3+
Location: /usr/local/lib/python2.7/dist-packages
Requires: lxml, jellyfish, urllib3, setuptools, diff-match-patch, Pillow, social-auth-core, djangorestframework, oauthlib, Django, translate-toolkit, Django, openpyxl, translation-finder, pathlib2, defusedxml, django-appconf, celery-batches, social-auth-app-django, backports.csv, celery, user-agents, html2text, python-dateutil, filelock, django-crispy-forms, six, siphashc, django-compressor, Whoosh
Required-by:`
