### ISSUE TITLE
ImportError: cannot import name 'Celery'

### ISSUE THREAD

**Issue by darthginger** [WeblateOrg/weblate#2420]
**Describe the bug**
This i think: [https://stackoverflow.com/questions/19926750/django-importerror-cannot-import-name-celery-possible-circular-import](https://stackoverflow.com/questions/19926750/django-importerror-cannot-import-name-celery-possible-circular-import)

**To Reproduce**
1. Install weblate using git; python dependencies like this: `python -m pip install celery`
2. Follow this [https://docs.weblate.org/en/latest/admin/install.html#background-tasks-using-celery](https://docs.weblate.org/en/latest/admin/install.html#background-tasks-using-celery)
3. run `systemctl start celery-weblate`
4. see error 
`systemd[1]: Starting Celery Service (Weblate)...`
`sh[25352]: Traceback (most recent call last):`
`sh[25352]:   File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main`
`sh[25352]:     "__main__", mod_spec)`
`sh[25352]:   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code`
`sh[25352]:     exec(code, run_globals)`
`sh[25352]:   File "/home/XXXXXX/weblate/weblate/celery.py", line 26, in <module>`
`sh[25352]:     from celery import Celery`
`sh[25352]:   File "/home/XXXXXX/weblate/weblate/celery.py", line 26, in <module>`
`sh[25352]:     from celery import Celery`
`sh[25352]: ImportError: cannot import name 'Celery'`
`sh[25352]: celery multi v4.2.1 (windowlicker)`
`sh[25352]: > Starting nodes...`
`sh[25352]:         > w1@XXXXXX.XX: * Child terminated with exit code 1`
`sh[25352]: FAILED`
`systemd[1]: celery-weblate.service: Control process exited, code=exited status=1`
`systemd[1]: celery-weblate.service: Failed with result 'exit-code'.`
`systemd[1]: Failed to start Celery Service (Weblate).`
`

**Expected behavior**
Celery service starts without error.

**Server configuration and status**
`./manage.py list_versions`
` * Weblate weblate-3.3`
` * Python 3.6.7`
` * Django 2.1.3`
` * Celery 4.2.1`
` * celery-batches 0.2`
` * six 1.11.0`
` * social-auth-core 2.0.0`
` * social-auth-app-django 3.1.0`
` * django-appconf 1.0.2`
` * translate-toolkit 2.3.1`
` * Whoosh 2.7.4`
` * defusedxml 0.5.0`
` * Git 2.19.2`
` * Pillow 5.3.0`
` * python-dateutil 2.7.5`
` * lxml 4.2.5`
` * django-crispy-forms 1.7.2`
` * django_compressor 2.2`
` * djangorestframework 3.9.0`
` * user-agents 1.1.0`
` * jellyfish 0.6.1`
` * pytz 2018.7`
` * pyuca 1.2`
` * Database backends: django.db.backends.mysql`
` * Cache backends: default:MemcachedCache, avatar:FileBasedCache`
` * Celery: amqp://norabbit4u:XXXXXXXXXX@localhost:5672/rabbithost, amqp://norabbit4u:XXXXXXXXXX@localhost:5672/rabbithost, regular`
` * Platform: Linux 4.18.0-2-amd64 (x86_64)`

**/etc/uwsgi/apps-available/weblate.uwsgi.ini**:
`[uwsgi]`
`plugins       = python`
`master        = true`
`protocol      = uwsgi`
`socket        = 127.0.0.1:8080`
`wsgi-file     = /home/XXXXXX/weblate/weblate/wsgi.py`
`python-path   = /home/XXXXXX/weblate`
`# In case you're using virtualenv uncomment this:`
`#virtualenv = /home/XXXXXX/weblate`
`# Needed for OAuth/OpenID`
`buffer-size   = 8192`
`# Increase number of workers for heavily loaded sites`
`#workers       = 6`
`# Needed for background processing`
`enable-threads = true`
`# Child processes do not need file descriptors`
`close-on-exec = true`
`# Avoid default 0000 umask`
`umask = 0022`

`pidfile2 = /tmp/uwsgi.pid`

**Additional context**
If i run `python celery.py` in `/home/XXXXXX/weblate/weblate/` i get this error aswell:
`Traceback (most recent call last):`
`  File "celery.py", line 26, in <module>`
`    from celery import Celery`
`  File "/home/XXXXXX/weblate/weblate/celery.py", line 26, in <module>`
`    from celery import Celery`
`ImportError: cannot import name 'Celery'`

If i rename celery.py to something else like celery_app.py it returns with no error like in the stackoverflow link.

`python --version`
Python 3.6.7

`import sys`
`print ('\n'.join(sys.path))`
returns
`/home/XXXXXX/weblate/weblate`
`/usr/lib/python36.zip`
`/usr/lib/python3.6`
`/usr/lib/python3.6/lib-dynload`
`/home/XXXXXX/.local/lib/python3.6/site-packages`
`/usr/local/lib/python3.6/dist-packages`
`/usr/lib/python3/dist-packages`

`python -m pip show celery`
returns
`Name: celery`
`Version: 4.2.1`
`Summary: Distributed Task Queue.`
`Home-page: http://celeryproject.org`
`Author: Ask Solem`
`Author-email: ask@celeryproject.org`
`License: BSD`
`Location: /home/XXXXXX/.local/lib/python3.6/site-packages`
`Requires: pytz, billiard, kombu`

**Comment by derN3rd** [comment]
I have the same problem after updating to 3.3 today.
Using virtualenv and installed via pip (python2.7), redis broker, always eager disabled

**Comment by nijel** [comment]
Duplicate of #2410

Most likely caused by wrongly configured python-path in uwsgi settings.

**Comment by darthginger** [comment]
not in my uwsgi settings but in my `/etc/systemd/system/celery-weblate.service`, The `WorkingDirectory=` had one too many `/weblate` appended.

But then i had a problem with rabbitmq.
Running `./manage.py check --deploy` gave this error:
`amqp.exceptions.PreconditionFailed: Queue.declare: (406) PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'celery' in vhost 'rabbithost': received 'false' but current is 'true'`
which i "fixed" by editing `weblate/utils/celery.py` last line to be:
`return conn.default_channel.queue_declare(queue='celery', durable=True, auto_delete=False).message_count`
(i got the same error with the auto_delete and the booleans switched after adding durable=True)
Now my weblate 3.3 is running.

**Comment by nijel** [comment]
I've changed it in 53dce9a9c1. It works both with redis which I'm using.
