### ISSUE TITLE
django.template.library.InvalidTemplateLibrary error when upgrading Weblate from 5.3.1 to 5.9.2

### ISSUE THREAD

**Issue by surli** [WeblateOrg/weblate#13494]
### Describe the issue

I'm performing an upgrade of Weblate from 5.3.1 to 5.9.2. I've checked before the upgrade that the software requirements was met and it seemed it was all good. I'm using a pypi installation so I ran `pip install -U "weblate[all]"` in my virtualenv, then I performed a backup of my settings.py and copied settings_example.py to edit that one directly to put my custom settings in it (to ensure I'm getting latest changes). Then I ran `weblate migrate --noinput` and here I'm getting the following error:
> django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'compressor.templatetags.compress': cannot import name 'get_storage_class' from 'django.core.files.storage' (/home/weblate/weblate-env/lib/python3.11/site-packages/django/core/files/storage/__init__.py)

I also tried to upgrade manually Django knowing that Weblate 5.6 release notes informed about the compatibiity to Django 5.1, so I called locally: `pip install Django[5.1] --upgrade --force-reinstall` and then tried again to run `weblate migrate --noinput` but without any difference in the result. 

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

I'm not sure it's possible to reproduce, but it would be:
  * Install and configure weblate 5.3.1 with pypi
  * Upgrade the pypi package
  * Fix the settings.py
  * Try to run `weblate migrate --noinput`

### Expected behavior

I was expecting to have the `weblate migrate --noinput` produce no error. 

### Exception traceback

```pytb
Traceback (most recent call last):
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/template/utils.py", line 69, in __getitem__
    return self._engines[alias]
           ~~~~~~~~~~~~~^^^^^^^
KeyError: 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/template/backends/django.py", line 174, in get_package_libraries
    module = import_module(entry[1])
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/compressor/templatetags/compress.py", line 4, in <module>
    from compressor.cache import (
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/compressor/cache.py", line 14, in <module>
    from compressor.storage import default_offline_manifest_storage
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/compressor/storage.py", line 7, in <module>
    from django.core.files.storage import FileSystemStorage, get_storage_class
ImportError: cannot import name 'get_storage_class' from 'django.core.files.storage' (/home/weblate/weblate-env/lib/python3.11/site-packages/django/core/files/storage/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/weblate/weblate-env/bin/weblate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/weblate/runner.py", line 19, in main
    utility.execute()
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/core/management/base.py", line 107, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 101, in handle
    self.check(databases=[database])
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/core/management/base.py", line 486, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/core/checks/templates.py", line 10, in check_templates
    for engine in engines.all():
                  ^^^^^^^^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/template/utils.py", line 94, in all
    return [self[alias] for alias in self]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/template/utils.py", line 94, in <listcomp>
    return [self[alias] for alias in self]
            ~~~~^^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/template/utils.py", line 85, in __getitem__
    engine = engine_cls(params)
             ^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/template/backends/django.py", line 26, in __init__
    options["libraries"] = self.get_templatetag_libraries(libraries)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/template/backends/django.py", line 88, in get_templatetag_libraries
    libraries = get_installed_libraries()
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/template/backends/django.py", line 162, in get_installed_libraries
    return {
           ^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/template/backends/django.py", line 162, in <dictcomp>
    return {
           ^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/template/backends/django.py", line 151, in get_template_tag_modules
    for name in get_package_libraries(pkg):
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/template/backends/django.py", line 176, in get_package_libraries
    raise InvalidTemplateLibrary(
django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'compressor.templatetags.compress': cannot import name 'get_storage_class' from 'django.core.files.storage' (/home/weblate/weblate-env/lib/python3.11/site-packages/django/core/files/storage/__init__.py)
```

### How do you run Weblate?

PyPI module

### Weblate versions

 * Weblate: 5.9.2
 * Django: 5.1.4
 * siphashc: 2.3
 * translate-toolkit: 3.14.5
 * lxml: 5.3.0
 * pillow: 11.1.0
 * nh3: 0.2.15
 * python-dateutil: 2.8.2
 * social-auth-core: 4.5.1
 * social-auth-app-django: 5.4.2
 * django-crispy-forms: 2.3
 * oauthlib: 3.2.2
 * django-compressor: 4.4
 * djangorestframework: 3.15.2
 * django-filter: 24.3
 * django-appconf: 1.0.6
 * user-agents: 2.2.0
 * filelock: 3.16.1
 * RapidFuzz: 3.11.0
 * openpyxl: 3.1.2
 * celery: 5.4.0
 * django-celery-beat: 2.7.0
 * kombu: 5.3.4
 * translation-finder: 2.19
 * weblate-language-data: 2024.16
 * html2text: 2024.2.26
 * pycairo: 1.25.1
 * PyGObject: 3.46.0
 * diff-match-patch: 20241021
 * requests: 2.32.3
 * django-redis: 5.4.0
 * hiredis: 2.2.3
 * sentry-sdk: 2.19.2
 * Cython: 3.0.11
 * mistletoe: 1.4.0
 * GitPython: 3.1.40
 * borgbackup: 1.2.7
 * pyparsing: 3.1.1
 * ahocorasick_rs: 0.22.1
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.3.2
 * cyrtranslit: 1.1.1
 * drf-spectacular: 0.28.0
 * Python: 3.11.2
 * Git: 2.39.5
 * psycopg: 3.1.17
 * psycopg-binary: 3.1.17
 * phply: 1.2.6
 * ruamel.yaml: 0.17.40
 * tesserocr: 2.6.2
 * boto3: 1.28.85
 * aeidon: 1.15
 * iniparse: 0.5
 * google-cloud-translate: 3.19.0
 * openai: 1.59.7
 * Mercurial: 6.9
 * git-review: 2.4.0
 * PostgreSQL server: 15.10
 * Database backends: django.db.backends.postgresql
 * PostgreSQL implementation: psycopg3 (binary)
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 6.1.0-17-amd64 (x86_64)

**Comment by nijel** [comment]
Seems like you've ended up with incompatible django-compressor and Django packages, upgrade django-compressor.

**Comment by surli** [comment]
> Seems like you've ended up with incompatible django-compressor and Django packages, upgrade django-compressor.

Thanks a lot, it was indeed the problem!
