### ISSUE TITLE
TypeError: auto_translate() got an unexpected keyword argument 'component' after upgrading to 5.17

### ISSUE THREAD

**Issue by Bubu** [WeblateOrg/weblate#19025]
### Describe the issue

(Context #18611)

After upgrading to 5.17, the background task queue emptied within 30s, but I think all(?) the tasks just crashed with an error:

```
Apr 15 11:29:59 translate ca5403b22682[246]: [2026-04-15 11:29:59,661: ERROR/437] Failure while executing task dc14c58a-b934-4c78-82e9-4725413a63fd
Apr 15 11:29:59 translate ca5403b22682[246]: Traceback (most recent call last):
Apr 15 11:29:59 translate ca5403b22682[246]:   File "/app/venv/lib/python3.14/site-packages/celery/app/trace.py", line 585, in trace_task
Apr 15 11:29:59 translate ca5403b22682[246]:     R = retval = fun(*args, **kwargs)
Apr 15 11:29:59 translate ca5403b22682[246]:                  ~~~^^^^^^^^^^^^^^^^^
Apr 15 11:29:59 translate ca5403b22682[246]:   File "/app/venv/lib/python3.14/site-packages/celery/app/trace.py", line 858, in __protected_call__
Apr 15 11:29:59 translate ca5403b22682[246]:     return self.run(*args, **kwargs)
Apr 15 11:29:59 translate ca5403b22682[246]:            ~~~~~~~~^^^^^^^^^^^^^^^^^
Apr 15 11:29:59 translate ca5403b22682[246]:   File "/app/venv/lib/python3.14/site-packages/celery/app/autoretry.py", line 38, in run
Apr 15 11:29:59 translate ca5403b22682[246]:     return task._orig_run(*args, **kwargs)
Apr 15 11:29:59 translate ca5403b22682[246]:            ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
Apr 15 11:29:59 translate ca5403b22682[246]: TypeError: auto_translate() got an unexpected keyword argument 'component'. Did you mean 'component_id'?
Apr 15 11:29:59 translate ca5403b22682[246]: [2026-04-15 11:29:59,661: ERROR/MainProcess] Failure while executing task dc14c58a-b934-4c78-82e9-4725413a63fd
Apr 15 11:29:59 translate ca5403b22682[246]: Traceback (most recent call last):
Apr 15 11:29:59 translate ca5403b22682[246]:   File "/app/venv/lib/python3.14/site-packages/celery/app/trace.py", line 585, in trace_task
Apr 15 11:29:59 translate ca5403b22682[246]:     R = retval = fun(*args, **kwargs)
```
Not sure if that is "expected" to happen when having these tasks around from before the upgrade? Where these tasks broken anyway? Is this a bug in the new version?

### I already tried

- [x] I've read and searched [the documentation](https://docs.weblate.org/).
- [x] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

See above and linked issue.

### Expected behavior

No exceptions in the log.

### Exception traceback

```pytb

```

### How do you run Weblate?

Docker container

### Weblate versions

5.17

### Weblate deploy checks

```shell

```

**Comment by nijel** [comment]
Sort of expected. The task queue was never considered a stable interface, so the expected upgrade process is with an empty queue. But I'm not sure if we properly document this or if it's something we're silently assuming.

**Comment by Bubu** [comment]
> Wait for the Celery queues to become empty.

That is not that easy when tasks take days/weeks to finish ;-).
