### ISSUE TITLE
Crashes after updating to 5.14

### ISSUE THREAD

**Issue by tipa** [WeblateOrg/weblate#16669]
### Describe the issue

After updating to v5.14, I am getting bombarded by Sentry errors and attempting to access the website fails with `500 Internal Server Error`.

I received over 60 mails from Sentry and each contain *a lot* for information, I hope the stack traces of two of them below contain enough context information, otherwise I am happy to provide more

### I already tried

- [x] I've read and searched [the documentation](https://docs.weblate.org/).
- [x] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

I just updated from 5.13 or 5.14

### Expected behavior

No exception

### Exception traceback

```pytb
Internal Server Error: /translate/MYPROJECT/app/de/

ImportError at /translate/MYPROJECT/app/de/
cannot import name 'ColPairs' from 'django.db.models.expressions' (/home/tp/weblate/lib64/python3.11/site-packages/django/db/models/expressions.py)

Request Method: GET
Request URL: https://MYDOMAIN.com/translate/MYPROJECT/app/de/?offset=161&q=state%3A%3E%3Dtranslated
Django Version: 5.1.6
Python Executable: /home/tp/weblate/bin/uwsgi
Python Version: 3.11.13
Python Path: ['/home/tp/weblate', '.', '', '/usr/lib64/python311.zip', '/usr/lib64/python3.11', '/usr/lib64/python3.11/lib-dynload', '/home/tp/weblate/lib64/python3.11/site-packages', '/home/tp/weblate/lib/python3.11/site-packages']
Server time: Wed, 22 Oct 2025 10:01:49 +0000
Installed Applications:
['weblate.addons',
 'weblate.auth',
 'weblate.checks',
 'weblate.formats',
 'weblate.glossary',
 'weblate.machinery',
 'weblate.trans',
 'weblate.lang',
 'weblate_language_data',
 'weblate.memory',
 'weblate.screenshots',
 'weblate.fonts',
 'weblate.accounts',
 'weblate.configuration',
 'weblate.utils',
 'weblate.vcs',
 'weblate.wladmin',
 'weblate.metrics',
 'weblate',
 'weblate.gitexport',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'django.contrib.sitemaps',
 'django.contrib.humanize',
 'social_django',
 'crispy_forms',
 'crispy_bootstrap3',
 'compressor',
 'rest_framework',
 'rest_framework.authtoken',
 'django_filters',
 'django_celery_beat',
 'corsheaders',
 'django_otp',
 'django_otp.plugins.otp_static',
 'django_otp.plugins.otp_totp',
 'django_otp_webauthn']
Installed Middleware:
['weblate.middleware.RedirectMiddleware',
 'weblate.middleware.ProxyMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'weblate.accounts.middleware.AuthenticationMiddleware',
 'django_otp.middleware.OTPMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'social_django.middleware.SocialAuthExceptionMiddleware',
 'weblate.accounts.middleware.RequireLoginMiddleware',
 'weblate.api.middleware.ThrottlingMiddleware',
 'weblate.middleware.SecurityMiddleware',
 'weblate.wladmin.middleware.ManageMiddleware']


Traceback (most recent call last):
  File "/home/tp/weblate/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/sentry_sdk/integrations/django/middleware.py", line 177, in __call__
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/weblate/accounts/middleware.py", line 54, in __call__
    from weblate.lang.models import Language
                          ^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/weblate/accounts/middleware.py", line 30, in get_user
    """
                   ^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/weblate/auth/models.py", line 389, in get_anonymous
    """Return an anonymous user."""
          
  File "/home/tp/weblate/lib64/python3.11/site-packages/django/db/models/query.py", line 645, in get
    return await sync_to_async(self.get)(*args, **kwargs)
          ^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/django/db/models/query.py", line 382, in __len__
    - Responsible for turning the rows into model objects.
^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    def _clone(self):
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/django/db/models/query.py", line 88, in __iter__
    compiler = queryset.query.get_compiler(using=db)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/django/db/models/sql/query.py", line 362, in get_compiler
    connection = connections[using]
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/django/db/backends/base/operations.py", line 392, in compiler
    self._cache = import_module(self.compiler_module)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
    <source code not available>
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
    <source code not available>
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
    <source code not available>
                         ^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
    <source code not available>
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
    <source code not available>
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
    <source code not available>
               ^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/django/db/models/sql/compiler.py", line 10, in <module>
    from django.db.models.expressions import ColPairs, F, OrderBy, RawSQL, Ref, Value

Exception Type: ImportError at /translate/MYPROJECT/app/de/
Exception Value: cannot import name 'ColPairs' from 'django.db.models.expressions' (/home/tp/weblate/lib64/python3.11/site-packages/django/db/models/expressions.py)
Raised during: weblate.trans.views.edit.translate
Request information:
USER: [unable to retrieve the current user]

GET:
offset = '161'
q = 'state:>=translated'

POST: No POST data

FILES: No FILES data

COOKIES: No cookie data

META:




-------------------



Internal Server Error: /

TemplateDoesNotExist at /
bootstrap5/field.html

Request Method: GET
Request URL: https://MYDOMAIN.com/
Django Version: 5.2.7
Python Executable: /home/tp/weblate/bin/uwsgi
Python Version: 3.11.14
Python Path: ['/home/tp/weblate', '.', '', '/usr/lib64/python311.zip', '/usr/lib64/python3.11', '/usr/lib64/python3.11/lib-dynload', '/home/tp/weblate/lib64/python3.11/site-packages', '/home/tp/weblate/lib/python3.11/site-packages']
Server time: Wed, 22 Oct 2025 10:20:32 +0000
Installed Applications:
['weblate.addons',
 'weblate.auth',
 'weblate.checks',
 'weblate.formats',
 'weblate.glossary',
 'weblate.machinery',
 'weblate.trans',
 'weblate.lang',
 'weblate_language_data',
 'weblate.memory',
 'weblate.screenshots',
 'weblate.fonts',
 'weblate.accounts',
 'weblate.configuration',
 'weblate.utils',
 'weblate.vcs',
 'weblate.wladmin',
 'weblate.metrics',
 'weblate',
 'weblate.gitexport',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'django.contrib.sitemaps',
 'django.contrib.humanize',
 'social_django',
 'crispy_forms',
 'crispy_bootstrap3',
 'compressor',
 'rest_framework',
 'rest_framework.authtoken',
 'django_filters',
 'django_celery_beat',
 'corsheaders',
 'django_otp',
 'django_otp.plugins.otp_static',
 'django_otp.plugins.otp_totp',
 'django_otp_webauthn']
Installed Middleware:
['weblate.middleware.RedirectMiddleware',
 'weblate.middleware.ProxyMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'weblate.accounts.middleware.AuthenticationMiddleware',
 'django_otp.middleware.OTPMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'social_django.middleware.SocialAuthExceptionMiddleware',
 'weblate.accounts.middleware.RequireLoginMiddleware',
 'weblate.api.middleware.ThrottlingMiddleware',
 'weblate.middleware.SecurityMiddleware',
 'weblate.wladmin.middleware.ManageMiddleware']
Template loader postmortem
Django tried loading these templates, in this order:

Using engine django:
    This engine did not provide a list of tried templates.




Traceback (most recent call last):
  File "/home/tp/weblate/lib64/python3.11/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/django/template/loader_tags.py", line 210, in render
    return template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/crispy_forms/templatetags/crispy_forms_tags.py", line 199, in render
    c = self.get_render(context).flatten()
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/crispy_forms/templatetags/crispy_forms_tags.py", line 117, in get_render
    actual_form.form_html = helper.render_layout(
                           
  File "/home/tp/weblate/lib64/python3.11/site-packages/crispy_forms/helper.py", line 276, in render_layout
    html = self.layout.render(form, context, template_pack=template_pack)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/crispy_forms/layout.py", line 142, in render
    return self.get_rendered_fields(form, context, template_pack, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/crispy_forms/layout.py", line 105, in get_rendered_fields
    "".join(render_field(field, form, context, template_pack=template_pack, **kwargs) for field in self.fields)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/crispy_forms/layout.py", line 105, in <genexpr>
    "".join(render_field(field, form, context, template_pack=template_pack, **kwargs) for field in self.fields)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/crispy_forms/utils.py", line 65, in render_field
    return field.render(form, context, template_pack=template_pack)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/crispy_forms/layout.py", line 748, in render
    fields = self.get_rendered_fields(form, context, template_pack, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/crispy_forms/layout.py", line 105, in get_rendered_fields
    "".join(render_field(field, form, context, template_pack=template_pack, **kwargs) for field in self.fields)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/crispy_forms/layout.py", line 105, in <genexpr>
    "".join(render_field(field, form, context, template_pack=template_pack, **kwargs) for field in self.fields)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/crispy_forms/utils.py", line 65, in render_field
    return field.render(form, context, template_pack=template_pack)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/crispy_forms/layout.py", line 947, in render
    return self.get_rendered_fields(
          
  File "/home/tp/weblate/lib64/python3.11/site-packages/crispy_forms/layout.py", line 105, in get_rendered_fields
    "".join(render_field(field, form, context, template_pack=template_pack, **kwargs) for field in self.fields)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/crispy_forms/layout.py", line 105, in <genexpr>
    "".join(render_field(field, form, context, template_pack=template_pack, **kwargs) for field in self.fields)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/crispy_forms/utils.py", line 118, in render_field
    template = get_template(template)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The above exception (bootstrap5/field.html) was the direct cause of the following exception:
  File "/home/tp/weblate/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/sentry_sdk/integrations/django/views.py", line 94, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/weblate/trans/views/dashboard.py", line 199, in home
    return dashboard_user(request)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/weblate/trans/views/dashboard.py", line 309, in dashboard_user
    return render(
          
  File "/home/tp/weblate/lib64/python3.11/site-packages/weblate/trans/util.py", line 280, in render
    return django.shortcuts.render(
          
  File "/home/tp/weblate/lib64/python3.11/site-packages/sentry_sdk/utils.py", line 1816, in runner
    return sentry_patched_function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/sentry_sdk/integrations/django/templates.py", line 105, in render
    return real_render(request, template_name, context, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/django/template/backends/django.py", line 109, in render
    reraise(exc, self.backend)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/weblate/lib64/python3.11/site-packages/django/template/backends/django.py", line 130, in reraise
    raise new from exc
    ^^^^^^^^^^^^^^^^^^

Exception Type: TemplateDoesNotExist at /
Exception Value: bootstrap5/field.html
Raised during: weblate.trans.views.dashboard.home
Request information:
USER: XXX

GET: No GET data

POST: No POST data

FILES: No FILES data

COOKIES:
_gumroad_guid = 'eb7147dc-0b46-4805-99a7-062f814e27ac'
sessionid = '********************'
django_language = 'en'

META:
```

### How do you run Weblate?

Other

### Weblate versions

5.14

### Weblate deploy checks

```shell

```
