### ISSUE TITLE
Celery: Module 'weblate' has no attribute 'celery'

### ISSUE THREAD

**Issue by Flohack74** [WeblateOrg/weblate#4047]
**Describe the bug**
After upgrading from Weblate 3.8 to 3.11 and applying all changes that were obvious (documentation, settings file compare) celery would not start anymore with this message:

Jun 16 18:18:28 t-ubports-localization sh[6199]: Error:
Jun 16 18:18:28 t-ubports-localization sh[6199]: Unable to load celery application.
Jun 16 18:18:28 t-ubports-localization sh[6199]: Module 'weblate' has no attribute 'celery'

I was only able to fix it with changing the default config in this weird way:

`CELERY_APP="weblate.utils"`

Is there anything obvious that I am missing here? Why does it not include that dir?

**Server configuration and status**
```
 * Weblate: 3.11.3
 * Django: 2.2.13
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 2.5.1
 * lxml: 4.5.1
 * Pillow: 7.0.0
 * bleach: 3.1.5
 * six: 1.14.0
 * python-dateutil: 2.8.1
 * social-auth-core: 3.2.0
 * social-auth-app-django: 3.1.0
 * django-crispy-forms: 1.8.1
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.0
 * django-appconf: 1.0.4
 * user-agents: 2.1
 * filelock: 3.0.12
 * setuptools: 47.3.0
 * jellyfish: 0.7.2
 * openpyxl: 2.6.4
 * celery: 4.4.5
 * kombu: 4.6.10
 * celery-batches: 0.3
 * translation-finder: 1.8
 * html2text: 2020.1.16
 * pycairo: 1.19.1
 * pygobject: 3.36.1
 * diff-match-patch: 20181111
 * requests: 2.23.0
 * django-redis: 4.11.0
 * hiredis: 1.0.1
 * sentry_sdk: 0.14.4
 * Cython: 0.29.20
 * misaka: 2.1.1
 * GitPython: 3.1.3
 * borgbackup: 1.1.13
 * Python: 3.5.2
 * Git: 2.7.4
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.10
 * hub: 2.7.4
 * Database backends: django.db.backends.mysql
 * Cache backends: avatar:FileBasedCache, default:MemcachedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: box.ubports.com
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 4.4.0-184-generic (x86_64)

SystemCheckError: System check identified some issues:

ERRORS:
?: (weblate.E006) Please migrate your database to use PostgreSQL. Support for other database backends will be dropped in Weblate 4.0 currently sheduled on April 2020.
        HINT: https://docs.weblate.org/en/weblate-3.11.3/admin/install.html#production-database

WARNINGS:
?: (security.W021) You have not set the SECURE_HSTS_PRELOAD setting to True. Without this, your site cannot be submitted to the browser preload list.
?: (weblate.W025.ass) Failure in loading handler for ass file format: aeidon or gaupol package required for Subtitle support
        HINT: https://docs.weblate.org/en/weblate-3.11.3/admin/install.html#optional-deps
?: (weblate.W025.srt) Failure in loading handler for srt file format: aeidon or gaupol package required for Subtitle support
        HINT: https://docs.weblate.org/en/weblate-3.11.3/admin/install.html#optional-deps
?: (weblate.W025.ssa) Failure in loading handler for ssa file format: aeidon or gaupol package required for Subtitle support
        HINT: https://docs.weblate.org/en/weblate-3.11.3/admin/install.html#optional-deps
?: (weblate.W025.sub) Failure in loading handler for sub file format: aeidon or gaupol package required for Subtitle support
        HINT: https://docs.weblate.org/en/weblate-3.11.3/admin/install.html#optional-deps

INFOS:
?: (weblate.I021) Error collection is not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-3.11.3/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-3.11.3/admin/backup.html
?: (weblate.I031) New Weblate version is available, please upgrade to 4.1.
        HINT: https://docs.weblate.org/en/weblate-3.11.3/admin/upgrade.html

```

**Comment by nijel** [comment]
This is expected, see https://docs.weblate.org/en/latest/admin/upgrade.html#upgrade-from-3-10-to-3-11 (also see ff19e75535de040e167cf8a26e6b9016d51eae37 and #3489).

**Comment by Flohack74** [comment]
Ok I read this page 5 times but did not see it ;) thanks!
