### ISSUE TITLE
msgmerge hook throws error

### ISSUE THREAD

**Issue by Flohack74** [WeblateOrg/weblate#3016]
**Describe the bug**
After following a few issues here I hoped that our msgmerge issue will go away after upgrading to 3.7.1 - Unfortunately it did not, it gets triggered now but with an error...

**To Reproduce**
1. Commit new changes in a Github repo
2. Github hook is triggered and notifies Weblate
3. Weblate pulls changes successfully
4. See error below

**Expected behavior**
msgmerge is executed and updates the po files

**Server configuration and status**
Please paste the output of `list_versions` and `check --deploy` commands over
here. Depending on installation these can be executed in different way, please
consult https://docs.weblate.org/en/latest/admin/management.html for more
details.

**Additional context**
```
[2019-09-12 10:39:25,267: INFO/ForkPoolWorker-3] ubports/teleports: rebase remote into repo
[2019-09-12 10:39:25,291: DEBUG/ForkPoolWorker-3] ubports/teleports: running post_update addon: weblate.gettext.msgmerge
[2019-09-12 10:39:25,297: INFO/ForkPoolWorker-3] Lock 140540222238504 released on /opt/weblate3/data/vcs/ubports/teleports.lock
[2019-09-12 10:39:25,304: ERROR/ForkPoolWorker-3] Task weblate.trans.tasks.perform_update[bdb5ce70-70c8-4113-a28b-44585a5a588e] raised unexpected: ImproperlyConfigured('Error importing module weblate.addons.gettext in WEBLATE_ADDONS: "cannot import name \'EVENT_DAILY\'"',)
Traceback (most recent call last):
  File "/opt/weblate3/local/lib/python3.5/site-packages/weblate/utils/classloader.py", line 39, in load_class
    mod = import_module(module)
  File "/opt/weblate3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/opt/weblate3/local/lib/python3.5/site-packages/weblate/addons/gettext.py", line 30, in <module>
    from weblate.addons.base import BaseAddon, StoreBaseAddon, UpdateBaseAddon
  File "/opt/weblate3/local/lib/python3.5/site-packages/weblate/addons/base.py", line 30, in <module>
    from weblate.addons.events import (
ImportError: cannot import name 'EVENT_DAILY'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/weblate3/local/lib/python3.5/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/weblate3/local/lib/python3.5/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/weblate3/local/lib/python3.5/site-packages/weblate/trans/tasks.py", line 61, in perform_update
```

**Comment by nijel** [comment]
Maybe you're running parts of old code? Possibly stale pyc files owned by different user?

**Comment by Flohack74** [comment]
Ok so I try to cleanup all .pyc and then report back, thx!

**Comment by Flohack74** [comment]
Hmm I dont get it, I checked base.py and events.py and the have this entry, but also after cleaning all pyc the error persists...

**Comment by Flohack74** [comment]
As I cannot constantly do commits to the repo to trigger this action, can I manually trigger the celery task for a specific repo to run the addon?

**Comment by nijel** [comment]
What should be enough to trigger this error is:

```
./manage.py shell -c 'import weblate.addons.gettext'
```

The full cleanup of stale compiled files can be done using:

```
find /opt/weblate3/local/lib/python3.5/site-packages/weblate -name '*.py[co]' -delete
```

**Comment by Flohack74** [comment]
Hmm I upgraded to Weblate 3.8 and finally it seems to work. WIll monitor a bit though :) thx
