### ISSUE TITLE
'NoneType' object has no attribute 'tab_slug'

### ISSUE THREAD

**Issue by fisharebest** [WeblateOrg/weblate#2369]
After upgrading from 2.13 to 2.16, I get the following error:

```
AttributeError at /
'NoneType' object has no attribute 'tab_slug'

Request Method: GET
Request URL: https://translate.webtrees.net/
Django Version: 1.11.16
Python Executable: /usr/bin/uwsgi-core
Python Version: 2.7.12
Python Path: ['/home/webtrees/weblate/', '.', '', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
Server time: Sun, 4 Nov 2018 18:48:54 +0000
Installed Applications:
(u'weblate.wladmin',
 u'django.contrib.auth',
 u'django.contrib.contenttypes',
 u'django.contrib.sessions',
 u'django.contrib.sites',
 u'django.contrib.messages',
 u'django.contrib.staticfiles',
 u'django.contrib.admin.apps.SimpleAdminConfig',
 u'django.contrib.admindocs',
 u'django.contrib.sitemaps',
 u'social_django',
 u'crispy_forms',
 u'compressor',
 u'rest_framework',
 u'rest_framework.authtoken',
 u'weblate.trans',
 u'weblate.lang',
 u'weblate.permissions',
 u'weblate.screenshots',
 u'weblate.accounts',
 u'weblate.utils',
 u'weblate')
Installed Middleware:
(u'django.contrib.sessions.middleware.SessionMiddleware',
 u'django.middleware.common.CommonMiddleware',
 u'django.middleware.locale.LocaleMiddleware',
 u'django.middleware.csrf.CsrfViewMiddleware',
 u'weblate.accounts.middleware.AuthenticationMiddleware',
 u'django.contrib.messages.middleware.MessageMiddleware',
 u'django.middleware.clickjacking.XFrameOptionsMiddleware',
 u'social_django.middleware.SocialAuthExceptionMiddleware',
 u'weblate.accounts.middleware.RequireLoginMiddleware',
 u'weblate.middleware.SecurityMiddleware')


Traceback: 

File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py" in _wrapped_view_func
  57.         response = view_func(request, *args, **kwargs)

File "/home/webtrees/weblate/weblate/trans/views/basic.py" in home
  191.         active_tab_slug = clist.tab_slug()
```

FYI, my upgrade script is:

```
sudo service uwsgi stop
git checkout weblate-2.16
vimdiff weblate/settings_example.py weblate/settings.py
sudo -H pip install --upgrade -r requirements.txt
sudo -H pip install --upgrade -r requirements-optional.txt
./manage.py migrate --noinput
./manage.py collectstatic --noinput
./manage.py setuplang
./manage.py setupgroups
./manage.py compilemessages
find . -name '*.pyc' -delete
sudo service uwsgi start
```

**Server configuration and status**

```
./manage.py list_versions

 * Weblate weblate-2.16
 * Python 2.7.12
 * Django 1.11.16
 * six 1.11.0
 * social-auth-core 2.0.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.3.1
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.7.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.7.5
 * lxml 4.2.5
 * django-crispy-forms 1.7.2
 * compressor 2.2
 * djangorestframework 3.9.0
 * pytz 2018.7
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.13
 * tesserocr 2.3.1
 * Mercurial 4.8
 * Database backends: django.db.backends.mysql
```

```
./manage.py check --deploy

?: (security.W001) You do not have 'django.middleware.security.SecurityMiddleware' in your MIDDLEWARE_CLASSES so the SECURE_HSTS_SECONDS, SECURE_CONTENT_TYPE_NOSNIFF, SECURE_BROWSER_XSS_FILTER, and SECURE_SSL_REDIRECT settings will have no effect.
?: (security.W019) You have 'django.middleware.clickjacking.XFrameOptionsMiddleware' in your MIDDLEWARE_CLASSES, but X_FRAME_OPTIONS is not set to 'DENY'. The default is 'SAMEORIGIN', but unless there is a good reason for your site to serve other parts of itself in a frame, you should change it to 'DENY'.
```

**Comment by nijel** [comment]
Did you somehow manually adjust user profiles? This case should be handled by model validation...

**Comment by fisharebest** [comment]
> Did you somehow manually adjust user profiles?

No.

I try to use defaults for everything.

**Comment by fisharebest** [comment]
Is this something I can fix by updating my database, configuration, etc.?

**Comment by fisharebest** [comment]
FYI, I have reverted to a backup of 2.10, and then upgraded sucessfully to 2.11.

The upgrade to 2.12 takes many hours.  I tried twice, but had errors each time.
I won't have time to try again for a few weeks.

If you want to close this issue, then go ahead.

I can open a new issue if my next attempt at upgrading fails.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
